Add scripting for non-terminal bus controller
ni/niveristand-ballard-milStd1553-custom-device pull request #244
Opened 2023-03-23 16:34 UTC by papowerNI

- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-ballard-milStd1553-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Update the scripting calls and associated unit tests for a bus controller that doesn't use RT zero.

### Why should this Pull Request be merged?

removes blocking RT 0 with a bus controller in the scripting API.

### What testing has been done?

Unit tests are all passing with only changes to the inputs to match the edits:
![image](https://user-images.githubusercontent.com/42351034/227272275-626fca52-fdde-498b-a6e2-8e75f1a67b52.png)

2023-03-23 18:14 UTC, buckd requested changes

2023-03-23 18:14 UTC, buckd commented on Source/Custom Device Support/Scripting/Port/Read Remote Terminals.vi
typo in comment 
![image](https://user-images.githubusercontent.com/29306186/227304023-ddc6e501-1853-42af-b650-ab777b98aafe.png)

2023-03-23 18:14 UTC, buckd commented on Source/Custom Device Support/Scripting/Port/Read Bus Controller and Acyclic Frames.vi
In the scripting library, move this VI under the `Port` virtual folder and save the library.
![image](https://user-images.githubusercontent.com/29306186/227306224-67c3d002-c30d-4ad6-a5c9-90ca788a5e3c.png)

2023-03-23 18:14 UTC, buckd commented on Source/Custom Device Support/Scripting/Message/Add Mode Code.vi
Make the `99` value a constant in `Scripting:Constants.vi` in case we need to use it anywhere else, so we don't have to track down all the places again in the future.
![image](https://user-images.githubusercontent.com/29306186/227307233-948b3a6c-2054-426b-8dca-0863d37d4099.png)

2023-03-23 18:14 UTC, buckd commented on Source/Custom Device Support/Scripting/Message/Get Remote Terminal Endpoint.vi
This constant should come from `Constants.vi` as mentioned above.
![image](https://user-images.githubusercontent.com/29306186/227307624-49515dc3-7431-4329-97c5-d7eae218fd3a.png)

2023-03-23 22:50 UTC, papowerNI commented on Source/Custom Device Support/Scripting/Message/Add Mode Code.vi
9a5b6ea38e8866a9ffdc60ea1438f8bc872b16cb

2023-03-23 22:50 UTC, papowerNI commented on Source/Custom Device Support/Scripting/Port/Read Bus Controller and Acyclic Frames.vi
9a5b6ea38e8866a9ffdc60ea1438f8bc872b16cb

2023-03-23 22:50 UTC, papowerNI commented on Source/Custom Device Support/Scripting/Port/Read Bus Controller and Acyclic Frames.vi
9a5b6ea38e8866a9ffdc60ea1438f8bc872b16cb

2023-03-23 22:52 UTC, papowerNI commented on Source/Custom Device Support/Scripting/Port/Read Remote Terminals.vi
d6993a8650c02ed4a7d7deb747740e928dc580cf

2023-03-24 13:27 UTC, buckd approved these changes

2023-03-24 13:30 UTC, merged